apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aibuddy-certificate
  namespace: default
spec:
  secretName: aibuddy-certificate
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: aibuddy.himanshuk.in
  dnsNames:
    - aibuddy.himanshuk.in
    - www.aibuddy.himanshuk.in
    - '*.aibuddy.himanshuk.in'
