apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 2121997him@gmail.com  # your email address for updates
    privateKeySecretRef:
      name: letsencrypt-dns01-private-key
    solvers:
    - dns01:
        cloudflare:
          email: 2121997him@gmail.com # your cloudflare account email address
          apiTokenSecretRef:
            name: cloudflare-api-key-secret # same name as setup-cluster secret set name
            key: api-key
