from node:20-alpine as server

workdir /app
RUN npm install -g bun
copy package*.json ./
copy prisma ./prisma/
run npm install

copy . .
expose 3000
# cmd ["bun","index.ts"]
cmd ["sh","-c","bun run db:deploy && bun index.ts"]