from node:20-alpine as client

workdir /app

copy . .
run npm install
run npm run build

# nginx - for reverse prox 

from nginx:alpine

copy --from=client /app/dist /usr/share/nginx/html
copy ./nginx.conf /etc/nginx/conf.d/default.conf
expose 80
cmd ["nginx", "-g", "daemon off;"]