FROM oven/bun:alpine AS deps
WORKDIR /app
RUN apk add --no-cache openssl
COPY package*.json ./
COPY prisma ./prisma/
RUN bun install
RUN bunx prisma generate

FROM oven/bun:alpine AS server
WORKDIR /app
RUN apk add --no-cache openssl
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/prisma ./prisma
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "bun run db:deploy && bun index.ts"]