version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ../.env
    ports:
      - 5432:5432


  client:
    build:
      context: ../client
      dockerfile: ../dockerfiles/dockerfile.client
    ports:
      - 80:80
    environment:
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - ../.env
    depends_on:
      - server
  
  server:
    build:
      context: ..
      dockerfile: ./dockerfiles/dockerfile.server
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_TOKEN=${TWILIO_TOKEN}
      - EMAIL_KEY=${EMAIL_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
      - TOTP_SECRET=${TOTP_SECRET}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - VM_IP=${VM_IP}
    env_file:
      - ../.env

