from node:22-alpine as client

workdir /app
copy package*.json .
run npm install
copy . .
run npm run build

# nginx - for reverse prox 

from nginx:alpine

copy --from=client /app/dist /usr/share/nginx/html
copy ./nginx.conf /etc/nginx/conf.d/default.conf
expose 80
cmd ["nginx", "-g", "daemon off;"]