FROM oven/bun:alpine AS deps
WORKDIR /app
COPY package*.json bun.lockb ./
COPY prisma ./prisma/
RUN bun install --frozen-lockfile --production

FROM oven/bun:alpine AS server
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/prisma ./prisma
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "bun run db:deploy && bun index.ts"]