#  to add code to docker hub, github actions used
name: ci-prod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Build and Push Frontend and Backend Images to docker hub
        run: |
          docker-compose -f dockerfiles/docker-compose.yml up -d