#  to add code to docker hub, github actions used
name: ci-prod
on:
  pull_request:
    types: [closed]
    branches: [main,master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Build and Push Frontend and Backend Images to docker hub
        run: |
          docker compose -f dockerfiles/docker-compose.yml build
          docker compose -f dockerfiles/docker-compose.yml push