name:Deploy-aibuddy
on: [push, workflow_dispatch]
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      EMAIL_KEY: ${{ secrets.EMAIL_KEY }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      VM_IP: ${{ secrets.VM_IP }}
    steps:
      - name: Deploy to server
        uses: actions/checkout@v3

      - name: Install dependencies
        run:
            docker-compose -f dockerfiles/docker-compose.yml up -d








# NODE_ENV=production
#       - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
#       - TWILIO_SID=${TWILIO_SID}
#       - TWILIO_TOKEN=${TWILIO_TOKEN}
#       - EMAIL_KEY=${EMAIL_KEY}
#       - FROM_EMAIL=${FROM_EMAIL}
#       - JWT_SECRET=${JWT_SECRET}
#       - TOTP_SECRET=${TOTP_SECRET}
#       - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
#       - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#       - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#       - FRONTEND_URL=${FRONTEND_URL}