name: Deployment Pipeline

on:
  pull_request:
    types: [closed]
    branches: [main,master]
  workflow_dispatch:

jobs:
  # CI: Build and push Docker images
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Build and Push Frontend and Backend Images to Docker Hub
        run: |
          docker compose -f dockerfiles/docker-compose.yml build
          docker compose -f dockerfiles/docker-compose.yml push

  # CD: Deploy to Kubernetes (on your VM running k3s)
  deploy-on-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0   # match your k3s version if needed

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Install Doppler CLI
        run: |
          if ! command -v doppler &> /dev/null; then
            curl -Ls https://cli.doppler.com/install.sh | sudo sh
          else
            echo "Doppler is already installed"
          fi

      - name: Sync Doppler secrets to K8s
        run: |
          export DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}
          doppler kubernetes secrets download \
            --project aibuddy \
            --config prd_himanshu \
            --name doppler-secrets \
            --create \
            --overwrite

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/db-deployment.yaml
          kubectl apply -f k8s/server-deployment.yaml
          kubectl apply -f k8s/client-deployment.yaml
